const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], DATA=window.DD2_DATA;
const icon={town:'🏠',quest:'📜',loot:'⚔️',dungeon:'🕳️',boss:'👹',merchant:'🛒',camp:'🏕️',token:'⭐',beetle:'🪲',portcrystal:'💠',vocation:'🧙',material:'⛏️'};
let custom=JSON.parse(localStorage.dd2_custom||'[]');
let state={view:'op',vocation:localStorage.dd2_vocation||'Fighter',q:'',region:'all',types:new Set(DATA.types),done:JSON.parse(localStorage.dd2_done||'{}'),scale:1,tx:0,ty:0,lastClick:null};
function allLocations(){return DATA.locations.concat(custom)}
function save(){localStorage.dd2_done=JSON.stringify(state.done);localStorage.dd2_vocation=state.vocation;localStorage.dd2_custom=JSON.stringify(custom)}
function init(){DATA.vocations.forEach(v=>$('#vocation').insertAdjacentHTML('beforeend',`<option ${v===state.vocation?'selected':''}>${v}</option>`)); DATA.types.forEach(t=>{$('#filters').insertAdjacentHTML('beforeend',`<button class="active" data-type="${t}">${icon[t]||'•'} ${t}</button>`);$('#newType').insertAdjacentHTML('beforeend',`<option>${t}</option>`)}); [...new Set(allLocations().map(x=>x.region))].sort().forEach(r=>$('#region').insertAdjacentHTML('beforeend',`<option>${r}</option>`)); bind(); render();}
function bind(){
 $('#vocation').onchange=e=>{state.vocation=e.target.value;save();render()}; $('#search').oninput=e=>{state.q=e.target.value.toLowerCase();render()}; $('#region').onchange=e=>{state.region=e.target.value;render()};
 $$('.tabs button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));render()});
 $('#filters').onclick=e=>{let b=e.target.closest('button'); if(!b)return; let t=b.dataset.type; state.types.has(t)?state.types.delete(t):state.types.add(t); b.classList.toggle('active'); render()};
 $('#zin').onclick=()=>zoom(1.22); $('#zout').onclick=()=>zoom(.82); $('#resetView').onclick=()=>{state.scale=1;state.tx=0;state.ty=0;applyTransform()}; $('#close').onclick=()=>$('#dlg').close();
 let vp=$('#mapViewport'), dragging=false, sx=0, sy=0, ox=0, oy=0; vp.addEventListener('pointerdown',e=>{dragging=true;sx=e.clientX;sy=e.clientY;ox=state.tx;oy=state.ty;vp.setPointerCapture(e.pointerId)}); vp.addEventListener('pointermove',e=>{if(!dragging)return;state.tx=ox+e.clientX-sx;state.ty=oy+e.clientY-sy;applyTransform()}); vp.addEventListener('pointerup',e=>{dragging=false}); vp.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.1:.9)});
 $('#mapInner').addEventListener('click',e=>{if(state.view!=='admin')return; let rect=$('#mapInner img').getBoundingClientRect(); state.lastClick={x:((e.clientX-rect.left)/rect.width*100).toFixed(1),y:((e.clientY-rect.top)/rect.height*100).toFixed(1)}; $('#newName').placeholder=`Nieuwe marker op ${state.lastClick.x}, ${state.lastClick.y}`});
 $('#saveMarker').onclick=()=>{if(!state.lastClick||!$('#newName').value.trim())return alert('Klik eerst op de kaart en vul een naam in.'); custom.push({id:'custom_'+Date.now(),name:$('#newName').value.trim(),type:$('#newType').value,region:$('#newRegion').value||'Eigen',x:+state.lastClick.x,y:+state.lastClick.y,priority:3,level:+$('#newLevel').value||1,desc:'Eigen marker.',loot:[$('#newLoot').value].filter(Boolean),quests:[],bosses:[],vocations:[],map:['op','complete'],route:null}); save(); $('#newName').value=''; $('#newLoot').value=''; render()};
 $('#exportMarkers').onclick=()=>$('#exportBox').textContent=JSON.stringify(custom,null,2);
 let deferred; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false}); $('#installBtn').onclick=()=>{deferred?.prompt();$('#installBtn').hidden=true}; if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js');
}
function zoom(f){state.scale=Math.max(.75,Math.min(5,state.scale*f));applyTransform()} function applyTransform(){$('#mapInner').style.transform=`translate(${state.tx}px,${state.ty}px) scale(${state.scale})`}
function textOf(l){return [l.name,l.region,l.type,l.desc,...(l.loot||[]),...(l.quests||[]),...(l.bosses||[]),...(l.vocations||[])].join(' ').toLowerCase()}
function filtered(){return allLocations().filter(l=>{let onMap=state.view==='admin'||(l.map||[]).includes(state.view); let voc=state.view!=='op'||!l.vocations?.length||l.vocations.includes(state.vocation); return onMap&&state.types.has(l.type)&&voc&&(state.region==='all'||l.region===state.region)&&(!state.q||textOf(l).includes(state.q))}).sort((a,b)=>(a.route||99)-(b.route||99)||b.priority-a.priority||a.level-b.level)}
function render(){let mapMode=state.view==='op'||state.view==='complete'||state.view==='admin'; $('.layout').classList.toggle('hidden',!mapMode); $('#dbView').classList.toggle('hidden',state.view!=='database'); $('#adminView').classList.toggle('hidden',state.view!=='admin'); if(mapMode){let list=filtered(); renderMarkers(list); renderList(list); renderStats(list); $('#mapInfo').textContent=state.view==='op'?'OP-route · '+state.vocation:state.view==='complete'?'100% completion':'Klik om markers te plaatsen'} if(state.view==='database')renderDB();}
function renderMarkers(list){$('#markers').innerHTML=''; list.forEach(l=>{let b=document.createElement('button'); b.className=`marker p${l.priority||3} ${state.done[l.id]?'done':''}`; b.style.left=l.x+'%'; b.style.top=l.y+'%'; b.innerHTML=icon[l.type]||'•'; b.title=l.name; b.onclick=e=>{e.stopPropagation();openDetail(l)}; $('#markers').appendChild(b)}); let route=list.filter(l=>state.view==='op'&&l.route).sort((a,b)=>a.route-b.route); $('#route').innerHTML=route.length>1?`<polyline points="${route.map(l=>`${l.x},${l.y}`).join(' ')}"/>`:'';}
function renderStats(list){let d=list.filter(l=>state.done[l.id]).length; $('#stats').innerHTML=`<div class="stat"><b>${list.length}</b><span>zichtbaar</span></div><div class="stat"><b>${d}</b><span>gedaan</span></div><div class="stat"><b>${Math.round(d/Math.max(1,list.length)*100)}%</b><span>klaar</span></div>`}
function renderList(list){$('#panelTitle').textContent=state.view==='op'?'Aanbevolen route voor '+state.vocation:state.view==='admin'?'Markers op kaart':'Complete checklist'; $('#list').innerHTML=list.map(l=>`<div class="card"><h3>${state.done[l.id]?'✅':'☐'} ${l.route&&state.view==='op'?l.route+'. ':''}${l.name}</h3><div class="meta">${l.region} · level ${l.level}+ · ${'⭐'.repeat(l.priority||3)}</div><div class="badges"><span class="badge">${icon[l.type]||'•'} ${l.type}</span>${(l.vocations||[]).slice(0,3).map(v=>`<span class="badge">${v}</span>`).join('')}</div><p>${l.desc}</p><div class="actions"><button class="small" onclick="openById('${l.id}')">Details</button><button class="small" onclick="toggleDone('${l.id}')">${state.done[l.id]?'Niet gedaan':'Gedaan'}</button><button class="small" onclick="centerOn('${l.id}')">Toon</button></div></div>`).join('')||'<p>Geen resultaten.</p>'}
function renderDB(){let q=state.q; let rows=[...DATA.gear.map(x=>({...x,cat:'Gear'})),...DATA.quests.map(x=>({name:x.name,type:'quest',vocation:'All',where:x.region,note:x.spoiler,cat:'Quest'}))].filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)); $('#dbList').innerHTML=rows.map(r=>`<div class="dbrow"><b>${r.cat}: ${r.name}</b><span>${r.type||''} · ${r.vocation||''}</span><span>${r.where||r.region||''}<br>${r.note||r.spoiler||''}</span></div>`).join('')}
window.toggleDone=id=>{state.done[id]=!state.done[id];save();render()}; window.openById=id=>openDetail(allLocations().find(x=>x.id===id)); window.centerOn=id=>{let l=allLocations().find(x=>x.id===id), vp=$('#mapViewport'), img=$('#mapInner img'); state.scale=Math.max(state.scale,2.2); state.tx=vp.clientWidth/2-(l.x/100*img.clientWidth*state.scale); state.ty=vp.clientHeight/2-(l.y/100*img.clientHeight*state.scale); applyTransform()};
function openDetail(l){$('#detail').innerHTML=`<h2>${l.name}</h2><p class="meta">${l.region} · ${icon[l.type]||'•'} ${l.type} · level ${l.level}+ · spoilers aan</p><p class="tip">${l.desc}</p><div class="cols"><section><h3>Loot / beloning</h3><ul>${(l.loot||[]).map(x=>`<li>${x}</li>`).join('')||'<li>Geen specifieke loot</li>'}</ul></section><section><h3>Quests</h3><ul>${(l.quests||[]).map(x=>`<li>${x}</li>`).join('')||'<li>Geen quest</li>'}</ul></section><section><h3>Bazen / vijanden</h3><ul>${(l.bosses||[]).map(x=>`<li>${x}</li>`).join('')||'<li>Geen boss</li>'}</ul></section><section><h3>Teun OP-advies</h3><ul><li>Speel Fighter, maar unlock Warrior/Sorcerer vroeg via Trevo Mine.</li><li>Pak Portcrystal/Ferrystone routes vroeg, zodat je minder hoeft te lopen.</li><li>Rust bij een inn vóór grote story-stappen en missable quests.</li></ul></section></div><button onclick="toggleDone('${l.id}');document.querySelector('#dlg').close()">${state.done[l.id]?'Markeer als niet gedaan':'Markeer als gedaan'}</button>`; $('#dlg').showModal()}
init();
